import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { LayoutDashboard, CalendarDays, Users, HardHat, BriefcaseBusiness, WalletCards, Star, ChartNoAxesCombined, Settings, Search, Bell, Menu, X, Eye, Pencil, CheckCircle2, Clock3, MapPin, Phone, CreditCard, UserRound, LogOut, Wrench, ClipboardList, CalendarCheck, CircleDollarSign, ChevronRight, Plus, SlidersHorizontal, ShieldCheck, Navigation, Camera, Check, AlertCircle, Heart, Filter } from 'lucide-react';
import './styles.css';

const bookings=[
{id:'BK-1042',customer:'Aisha Rahman',service:'AC Repair',tech:'Ravi Kumar',date:'Sep 01, 2026',time:'10:00 AM',amount:'AED 1,200',status:'Confirmed',address:'Dubai Marina'},
{id:'BK-1041',customer:'James Osei',service:'Plumbing Fix',tech:'Suresh Nair',date:'Sep 01, 2026',time:'11:30 AM',amount:'AED 850',status:'In Progress',address:'JLT'},
{id:'BK-1040',customer:'Priya Sharma',service:'Electrical Wiring',tech:'Ali Hassan',date:'Sep 01, 2026',time:'02:00 PM',amount:'AED 2,200',status:'Pending',address:'Downtown Dubai'},
{id:'BK-1039',customer:'Carlos Mendez',service:'Washing Machine Repair',tech:'Ravi Kumar',date:'Aug 31, 2026',time:'09:00 AM',amount:'AED 750',status:'Completed',address:'Business Bay'},
{id:'BK-1038',customer:'Fatima Al-Zahra',service:'Refrigerator Repair',tech:'Suresh Nair',date:'Aug 31, 2026',time:'03:00 PM',amount:'AED 1,100',status:'Completed',address:'Al Barsha'},
{id:'BK-1037',customer:'Liam Nguyen',service:'AC Installation',tech:'Ali Hassan',date:'Aug 30, 2026',time:'11:00 AM',amount:'AED 4,500',status:'Cancelled',address:'Dubai Hills'},
{id:'BK-1036',customer:'Sofia Ivanova',service:'Painting',tech:'Dev Patel',date:'Aug 30, 2026',time:'09:30 AM',amount:'AED 3,200',status:'Completed',address:'Jumeirah'},
{id:'BK-1035',customer:'Omar Abdullah',service:'Deep Cleaning',tech:'Ravi Kumar',date:'Aug 29, 2026',time:'08:00 AM',amount:'AED 1,800',status:'Completed',address:'Deira'}];
const customers=[
{name:'Aisha Rahman',phone:'+971 50 123 4567',email:'aisha@email.com',bookings:12,spent:'AED 14,800',last:'Sep 01, 2026',status:'Active'},
{name:'James Osei',phone:'+971 55 234 5678',email:'james@email.com',bookings:8,spent:'AED 9,200',last:'Sep 01, 2026',status:'Active'},
{name:'Priya Sharma',phone:'+971 52 345 6789',email:'priya@email.com',bookings:5,spent:'AED 7,600',last:'Sep 01, 2026',status:'Active'},
{name:'Carlos Mendez',phone:'+971 56 456 7890',email:'carlos@email.com',bookings:3,spent:'AED 3,400',last:'Aug 31, 2026',status:'Active'},
{name:'Fatima Al-Zahra',phone:'+971 58 567 8901',email:'fatima@email.com',bookings:7,spent:'AED 8,900',last:'Aug 31, 2026',status:'Active'},
{name:'Liam Nguyen',phone:'+971 50 678 9012',email:'liam@email.com',bookings:2,spent:'AED 5,200',last:'Aug 30, 2026',status:'Inactive'},
{name:'Sofia Ivanova',phone:'+971 55 789 0123',email:'sofia@email.com',bookings:9,spent:'AED 11,400',last:'Aug 30, 2026',status:'Active'},
{name:'Omar Abdullah',phone:'+971 52 890 1234',email:'omar@email.com',bookings:6,spent:'AED 7,800',last:'Aug 29, 2026',status:'Active'}];
const technicians=[
{name:'Ravi Kumar',specialty:'AC & Refrigeration',area:'Dubai Marina',status:'On Job',rating:'4.9',jobs:'248',phone:'+971 50 222 1111'},
{name:'Suresh Nair',specialty:'Plumbing',area:'JLT',status:'On Job',rating:'4.8',jobs:'192',phone:'+971 55 222 1111'},
{name:'Ali Hassan',specialty:'Electrical',area:'Downtown Dubai',status:'Available',rating:'4.7',jobs:'175',phone:'+971 52 222 1111'},
{name:'Dev Patel',specialty:'Painting & Renovation',area:'Jumeirah',status:'Available',rating:'4.6',jobs:'143',phone:'+971 56 222 1111'},
{name:'Khalid Mansoor',specialty:'Deep Cleaning',area:'Deira',status:'Offline',rating:'4.8',jobs:'211',phone:'+971 58 222 1111'},
{name:'Nitin Sharma',specialty:'Appliance Repair',area:'Sharjah',status:'Available',rating:'4.5',jobs:'128',phone:'+971 50 333 1111'}];
const services=[
{icon:'❄️',name:'AC Repair',category:'HVAC',description:'Complete AC diagnostic, cleaning and repair service',price:'AED 1,200',duration:'2–3 hours',bookings:342,status:'Active'},
{icon:'🔧',name:'AC Installation',category:'HVAC',description:'Professional AC unit installation with full setup',price:'AED 4,500',duration:'4–5 hours',bookings:187,status:'Active'},
{icon:'🚿',name:'Plumbing Fix',category:'Plumbing',description:'Leak repair, pipe fitting, and drain cleaning',price:'AED 850',duration:'1–2 hours',bookings:289,status:'Active'},
{icon:'⚡',name:'Electrical Wiring',category:'Electrical',description:'Full electrical wiring, safety inspection, and fixture installation',price:'AED 2,200',duration:'3–4 hours',bookings:156,status:'Active'},
{icon:'🧹',name:'Deep Cleaning',category:'Cleaning',description:'Thorough home cleaning including kitchen, bathrooms, and all rooms',price:'AED 1,800',duration:'4–6 hours',bookings:412,status:'Active'},
{icon:'🏠',name:'Appliance Repair',category:'Appliances',description:'Washing machine, refrigerator, and home appliance repair',price:'AED 950',duration:'1–2 hours',bookings:234,status:'Active'},
{icon:'🎨',name:'Painting',category:'Renovation',description:'Interior wall painting with premium finishes',price:'AED 3,200',duration:'1–2 days',bookings:98,status:'Active'},
{icon:'🦟',name:'Pest Control',category:'Pest Control',description:'Comprehensive pest treatment and prevention',price:'AED 600',duration:'1–2 hours',bookings:76,status:'Inactive'}];
const reviews=['Aisha Rahman','James Osei','Sofia Ivanova','Omar Abdullah','Carlos Mendez','Fatima Al-Zahra'].map((name,i)=>({name,rating:i===4?3:5,service:i%2?'Plumbing Fix':'AC Repair',status:i%2?'Awaiting reply':'Replied',text:'Absolutely fantastic service! The technician was professional, punctual and completed the work perfectly. Will definitely book again.'}));
const adminNav=[['Dashboard',LayoutDashboard],['Bookings',CalendarDays],['Customers',Users],['Technicians',HardHat],['Services',BriefcaseBusiness],['Payments',WalletCards],['Reviews',Star],['Reports',ChartNoAxesCombined],['Settings',Settings]];
const techNav=[['Dashboard',LayoutDashboard],['My Jobs',ClipboardList],['Schedule',CalendarCheck],['Earnings',CircleDollarSign],['Reviews',Star],['Profile',UserRound],['Settings',Settings]];
const userNav=[['Dashboard',LayoutDashboard],['Services',BriefcaseBusiness],['My Bookings',CalendarDays],['Payments',WalletCards],['Reviews',Star],['Profile',UserRound],['Settings',Settings]];

function Status({children}){return <span className={'status '+String(children).toLowerCase().replace(/\s+/g,'-')}>{children}</span>}
function Avatar({name,size=''}){return <div className={'avatar '+size}>{name?.split(' ').map(x=>x[0]).join('').slice(0,2)}</div>}
function Button({children,variant='',onClick,type='button',icon}){return <button type={type} className={'btn '+variant} onClick={onClick}>{icon}{children}</button>}
function Stat({value,label,trend,icon}){return <div className="stat"><div className="stat-icon">{icon}</div><div><b>{value}</b><span>{label}</span>{trend&&<em>↑ {trend}</em>}</div></div>}
function Card({title,action,children,className=''}){return <section className={'card '+className}><div className="card-head">{title&&<h3>{title}</h3>}{action}</div>{children}</section>}
function PageTitle({title,subtitle,action}){return <div className="page-title"><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}
function Progress({name,value}){return <div className="progress"><span>{name}</span><div><i style={{width:`${Math.min(value,100)}%`}}/></div><b>{value}</b></div>}
function Activity({icon,text,time}){return <div className="activity"><span>{icon}</span><div><b>{text}</b><small>{time}</small></div></div>}
function Toolbar({q,setQ,filter,setFilter,options,placeholder}){return <div className="toolbar"><Search size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={placeholder}/><Filter size={17}/><select value={filter} onChange={e=>setFilter(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></div>}
function TableWrap({children}){return <div className="tablewrap">{children}</div>}

function AdminDashboard({go}){return <><PageTitle title="Dashboard" subtitle="Welcome back, Admin. Here’s what’s happening with your service business today."/><div className="stats"><Stat value="128" label="Total Bookings" trend="18% this week" icon={<CalendarDays/>}/><Stat value="343" label="Total Customers" trend="22% this week" icon={<Users/>}/><Stat value="28" label="Total Technicians" trend="12% this week" icon={<HardHat/>}/><Stat value="AED 366K" label="Total Revenue" trend="25% this month" icon={<WalletCards/>}/></div><div className="grid2"><Card title="Booking Overview"><div className="chart"><div className="chart-grid">{[38,58,45,78,65,92,72].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><div className="axis"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div></Card><Card title="Today’s Bookings" action={<Button variant="link" onClick={()=>go('Bookings')}>View all</Button>}><div className="today-list">{bookings.slice(0,4).map(b=><div className="today-row" key={b.id}><div className="time">{b.time}</div><Avatar name={b.customer}/><div className="grow"><b>{b.customer}</b><small>{b.service}</small></div><Status>{b.status}</Status></div>)}</div></Card></div><div className="grid3"><Card title="Top Services"><Progress name="AC Service" value={45}/><Progress name="Washing Machine Repair" value={32}/><Progress name="Plumbing Service" value={21}/><Progress name="Electrical Installation" value={18}/></Card><Card title="Technician Status"><div className="status-count"><div><span className="dot available"/>Available <b>12</b></div><div><span className="dot onjob"/>On Job <b>8</b></div><div><span className="dot offline"/>Offline <b>8</b></div></div></Card><Card title="Recent Activity"><Activity icon={<CalendarCheck/>} text="New booking received from John Doe" time="5 min ago"/><Activity icon={<CreditCard/>} text="Payment of AED 2,450 received" time="18 min ago"/><Activity icon={<Star/>} text="New 5-star review received" time="42 min ago"/></Card></div></>}
function AdminBookings({open}){const[q,setQ]=useState(''),[filter,setFilter]=useState('All');const rows=bookings.filter(b=>(filter==='All'||b.status===filter)&&Object.values(b).join(' ').toLowerCase().includes(q.toLowerCase()));return <><PageTitle title="Bookings" subtitle="Manage all customer service bookings and assignments." action={<Button icon={<Plus size={17}/>} onClick={()=>open({title:'Create Booking',form:true})}>New Booking</Button>}/><div className="stats compact"><Stat value="128" label="Total Bookings" icon={<CalendarDays/>}/><Stat value="94" label="Completed" icon={<CheckCircle2/>}/><Stat value="18" label="Pending" icon={<Clock3/>}/><Stat value="16" label="In Progress" icon={<Wrench/>}/></div><Toolbar q={q} setQ={setQ} filter={filter} setFilter={setFilter} options={['All','Confirmed','In Progress','Pending','Completed','Cancelled']} placeholder="Search booking ID, customer..."/><TableWrap><table><thead><tr>{['Booking ID','Customer','Service','Technician','Date & Time','Amount','Status','Actions'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(b=><tr key={b.id}><td className="linkish">{b.id}</td><td><div className="person"><Avatar name={b.customer}/><b>{b.customer}</b></div></td><td>{b.service}</td><td>{b.tech}</td><td>{b.date}<small>{b.time}</small></td><td><b>{b.amount}</b></td><td><Status>{b.status}</Status></td><td><Button variant="small" onClick={()=>open({title:`Booking ${b.id}`,booking:b})}><Eye size={14}/>View</Button><Button variant="small soft" onClick={()=>open({title:'Edit Booking',booking:b,form:true})}><Pencil size={14}/>Edit</Button></td></tr>)}</tbody></table></TableWrap></>}
function AdminCustomers({open}){const[q,setQ]=useState(''),[filter,setFilter]=useState('All');const rows=customers.filter(c=>(filter==='All'||c.status===filter)&&Object.values(c).join(' ').toLowerCase().includes(q.toLowerCase()));return <><PageTitle title="Customers" subtitle="View customer accounts, history and contact information." action={<Button icon={<Plus size={17}/>} onClick={()=>open({title:'Add Customer',form:true})}>Add Customer</Button>}/><div className="stats compact"><Stat value="343" label="Total Customers" icon={<Users/>}/><Stat value="327" label="Active Customers" icon={<CheckCircle2/>}/><Stat value="42" label="New This Month" icon={<UserRound/>}/><Stat value="96%" label="Retention Rate" icon={<Heart/>}/></div><Toolbar q={q} setQ={setQ} filter={filter} setFilter={setFilter} options={['All','Active','Inactive']} placeholder="Search customer, phone, email..."/><TableWrap><table><thead><tr>{['Customer','Phone','Email','Bookings','Total Spent','Last Booking','Status','Actions'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(c=><tr key={c.email}><td><div className="person"><Avatar name={c.name}/><b>{c.name}</b></div></td><td>{c.phone}</td><td>{c.email}</td><td>{c.bookings}</td><td><b>{c.spent}</b></td><td>{c.last}</td><td><Status>{c.status}</Status></td><td><Button variant="small" onClick={()=>open({title:c.name,customer:c})}><Eye size={14}/>View</Button><Button variant="small soft" onClick={()=>open({title:'Edit Customer',customer:c,form:true})}><Pencil size={14}/>Edit</Button></td></tr>)}</tbody></table></TableWrap></>}
function AdminTechnicians({open}){const[q,setQ]=useState(''),[filter,setFilter]=useState('All');const rows=technicians.filter(t=>(filter==='All'||t.status===filter)&&Object.values(t).join(' ').toLowerCase().includes(q.toLowerCase()));return <><PageTitle title="Technicians" subtitle="Manage technicians, availability, skills and assignments." action={<Button icon={<Plus size={17}/>} onClick={()=>open({title:'Add Technician',form:true})}>Add Technician</Button>}/><div className="stats compact"><Stat value="28" label="Total" icon={<HardHat/>}/><Stat value="8" label="On Job" icon={<Wrench/>}/><Stat value="12" label="Available" icon={<CheckCircle2/>}/><Stat value="8" label="Offline" icon={<AlertCircle/>}/></div><Toolbar q={q} setQ={setQ} filter={filter} setFilter={setFilter} options={['All','Available','On Job','Offline']} placeholder="Search technicians..."/><div className="tech-grid">{rows.map(t=><div className="tech-card" key={t.name}><div className="tech-top"><Avatar name={t.name} size="large"/><Status>{t.status}</Status></div><h3>{t.name}</h3><p className="accent-text">{t.specialty}</p><p><MapPin size={14}/> {t.area}</p><div className="rating-line"><span>★★★★★</span><b>{t.rating}</b><small>{t.jobs} jobs</small></div><div className="tech-actions"><Button onClick={()=>open({title:t.name,technician:t})}>View Profile</Button><Button variant="soft" onClick={()=>open({title:'Assign Technician',technician:t,form:true})}>Assign Job</Button></div></div>)}</div></>}
function AdminServices({open}){const[q,setQ]=useState(''),[filter,setFilter]=useState('All');const rows=services.filter(s=>(filter==='All'||s.category===filter||s.status===filter)&&Object.values(s).join(' ').toLowerCase().includes(q.toLowerCase()));return <><PageTitle title="Services" subtitle="Create and manage the services customers can book." action={<Button icon={<Plus size={17}/>} onClick={()=>open({title:'Add Service',form:true})}>Add Service</Button>}/><div className="stats compact"><Stat value="8" label="Total Services" icon={<BriefcaseBusiness/>}/><Stat value="7" label="Active Services" icon={<CheckCircle2/>}/><Stat value="1,794" label="Total Bookings" icon={<CalendarDays/>}/><Stat value="7" label="Categories" icon={<SlidersHorizontal/>}/></div><Toolbar q={q} setQ={setQ} filter={filter} setFilter={setFilter} options={['All','HVAC','Plumbing','Electrical','Cleaning','Appliances','Renovation','Active','Inactive']} placeholder="Search services..."/><div className="service-grid">{rows.map(s=><div className="service-card" key={s.name}><div className="service-icon">{s.icon}</div><Status>{s.status}</Status><h3>{s.name}</h3><p className="accent-text">{s.category}</p><p className="description">{s.description}</p><div className="service-meta"><div><b>{s.price}</b><small>{s.duration}</small></div><div><b>{s.bookings}</b><small>bookings</small></div></div><div className="service-actions"><Button variant="small" onClick={()=>open({title:s.name,service:s})}>View</Button><Button variant="small soft" onClick={()=>open({title:'Edit Service',service:s,form:true})}>Edit</Button><Button variant="small danger" onClick={()=>open({title:s.status==='Active'?'Disable Service':'Enable Service',service:s,confirm:true})}>{s.status==='Active'?'Disable':'Enable'}</Button></div></div>)}</div></>}
function AdminPayments({open}){const[q,setQ]=useState('');return <><PageTitle title="Payments" subtitle="Track transactions, completed payments and refunds."/><div className="stats compact"><Stat value="AED 366K" label="Total Revenue" trend="18%" icon={<WalletCards/>}/><Stat value="AED 348K" label="Paid" icon={<CheckCircle2/>}/><Stat value="AED 18K" label="Pending" icon={<Clock3/>}/><Stat value="AED 4.5K" label="Refunded" icon={<AlertCircle/>}/></div><Toolbar q={q} setQ={setQ} filter="All" setFilter={()=>{}} options={['All']} placeholder="Search transactions..."/><TableWrap><table><thead><tr>{['Transaction ID','Customer','Booking','Service','Amount','Method','Date','Status','Actions'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{bookings.filter(b=>Object.values(b).join(' ').toLowerCase().includes(q.toLowerCase())).map((b,i)=><tr key={b.id}><td className="linkish">TX-{5521-i}</td><td>{b.customer}</td><td className="linkish">{b.id}</td><td>{b.service}</td><td><b>{b.amount}</b></td><td><CreditCard size={14}/> Credit Card</td><td>{b.date}</td><td><Status>{i===4?'Refunded':b.status==='Pending'?'Pending':'Paid'}</Status></td><td><Button variant="small" onClick={()=>open({title:`Transaction TX-${5521-i}`,payment:b})}><Eye size={14}/>View</Button></td></tr>)}</tbody></table></TableWrap></>}
function AdminReviews(){return <><PageTitle title="Reviews" subtitle="Monitor customer ratings and respond to feedback."/><div className="review-summary"><Card><div className="score"><strong>4.7</strong><div>★★★★★</div><span>1,248 total reviews</span></div></Card><Card title="Rating Breakdown"><Progress name="5 ★" value={88}/><Progress name="4 ★" value={8}/><Progress name="3 ★" value={3}/><Progress name="2 ★" value={1}/><Progress name="1 ★" value={1}/></Card></div><div className="review-grid">{reviews.map(r=><div className="review-card" key={r.name}><div className="person"><Avatar name={r.name}/><div><b>{r.name}</b><small>{r.service}</small></div></div><div className="stars">{'★'.repeat(r.rating)}<span>{'★'.repeat(5-r.rating)}</span></div><p>“{r.text}”</p><Status>{r.status}</Status><Button variant="small soft">{r.status==='Replied'?'Edit Reply':'Reply'}</Button></div>)}</div></>}
function AdminReports(){return <><PageTitle title="Reports" subtitle="Analyze bookings, revenue, customers and service performance."/><div className="period"><span>Period</span><button>Daily</button><button>Weekly</button><button className="active">Monthly</button><button>Yearly</button><b>March – September 2026</b></div><div className="stats compact"><Stat value="AED 366K" label="Total Revenue" trend="18%" icon={<WalletCards/>}/><Stat value="1,248" label="Total Bookings" trend="12%" icon={<CalendarDays/>}/><Stat value="+352" label="Customer Growth" trend="52%" icon={<Users/>}/><Stat value="4.7 ★" label="Average Rating" trend="0.2" icon={<Star/>}/></div><div className="grid2"><Card title="Revenue Overview"><div className="report-chart"><div className="bars">{[42,54,48,68,76,88,96].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><div className="axis"><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span></div></div></Card><Card title="Customer Growth"><div className="growth-chart"><div className="growth-line"/><strong>+352 customers</strong><small>Strong growth over the selected period</small></div></Card></div><div className="grid2"><Card title="Booking Trends"><div className="trend-chart">{[42,58,51,68,74,84,91].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></Card><Card title="Service Performance"><div className="donut-wrap"><div className="donut">72%</div><div><b>Best performing</b><p>AC Repair</p><small>342 bookings · AED 410K</small></div></div></Card></div></>}
function SettingsPage({role}){const name=role==='admin'?'Admin User':role==='technician'?'Ravi Kumar':'Aisha Rahman';return <><PageTitle title="Settings" subtitle="Manage account, notifications, security and application preferences."/><div className="settings-layout"><div className="settings-nav"><button className="active"><UserRound/>Profile</button><button><Bell/>Notifications</button><button><ShieldCheck/>Security</button><button><Settings/>Preferences</button></div><Card title="Profile Information"><div className="profile-edit"><Avatar name={name} size="xl"/><Button variant="soft"><Camera size={15}/>Change Photo</Button></div><div className="form-grid"><Field label="Full Name" value={name}/><Field label="Email" value="admin@clientservices.com"/><Field label="Phone" value="+971 50 123 4567"/><Field label="Language" value="English" select/></div><div className="form-actions"><Button>Save Changes</Button></div></Card></div></>}
function Field({label,value,select}){return <label className="field"><span>{label}</span>{select?<select defaultValue={value}><option>English</option><option>Arabic</option></select>:<input defaultValue={value}/>}</label>}

function TechDashboard({go}){return <><PageTitle title="Good morning, Ravi 👋" subtitle="Here’s your work overview for today." action={<div className="online-toggle"><span className="dot available"/>Available for jobs</div>}/><div className="stats"><Stat value="6" label="Today’s Jobs" icon={<ClipboardList/>}/><Stat value="4" label="Completed" icon={<CheckCircle2/>}/><Stat value="2" label="Upcoming" icon={<CalendarCheck/>}/><Stat value="AED 8,450" label="This Month" trend="14%" icon={<CircleDollarSign/>}/></div><div className="grid2"><Card title="Today’s Schedule" action={<Button variant="link" onClick={()=>go('Schedule')}>Full schedule</Button>}><JobList go={go}/></Card><Card title="Performance"><div className="performance"><div><strong>4.9</strong><span>★★★★★</span><small>248 completed jobs</small></div><div className="performance-bars"><Progress name="On-time" value={96}/><Progress name="Customer rating" value={98}/><Progress name="Job success" value={94}/></div></div></Card></div><div className="grid2"><Card title="New Job Request"><div className="request"><div className="request-icon"><Wrench/></div><div className="grow"><b>AC Repair · BK-1042</b><p>Aisha Rahman · Dubai Marina</p><small>Today, 10:00 AM · AED 1,200</small></div><Button onClick={()=>go('My Jobs')}>View Job</Button></div></Card><Card title="Quick Actions"><div className="quick-actions"><Button onClick={()=>go('Schedule')}><CalendarDays/>View Schedule</Button><Button onClick={()=>go('My Jobs')}><ClipboardList/>My Jobs</Button><Button><Navigation/>Open Map</Button></div></Card></div></>}
function JobList({go}){return <div className="job-list">{bookings.slice(0,4).map((b,i)=><div className="job-row" key={b.id}><div className="job-time">{b.time}<small>{i<2?'Today':'Tomorrow'}</small></div><div className="job-info"><b>{b.service}</b><span>{b.customer} · {b.address}</span></div><Status>{i<2?'Completed':i===2?'In Progress':'Confirmed'}</Status><button onClick={()=>go('My Jobs')}><ChevronRight/></button></div>)}</div>}
function TechJobs({open}){return <><PageTitle title="My Jobs" subtitle="Manage assigned service requests and update job progress."/><div className="tabs"><button className="active">All (6)</button><button>Upcoming (2)</button><button>In Progress (1)</button><button>Completed (3)</button></div><div className="job-cards">{bookings.slice(0,6).map((b,i)=><div className="job-card" key={b.id}><div className="job-card-head"><span className="linkish">{b.id}</span><Status>{i===0?'In Progress':i<3?'Confirmed':'Completed'}</Status></div><h3>{b.service}</h3><div className="job-customer"><Avatar name={b.customer}/><div><b>{b.customer}</b><small><MapPin size={13}/> {b.address}</small></div></div><div className="job-details"><span><CalendarDays/> {b.date}</span><span><Clock3/> {b.time}</span><span><CircleDollarSign/> {b.amount}</span></div><div className="job-card-actions"><Button onClick={()=>open({title:`Job ${b.id}`,booking:b,technicianJob:true})}>View Details</Button>{i===0&&<Button variant="soft" onClick={()=>open({title:'Update Job',booking:b,form:true})}>Update Status</Button>}</div></div>)}</div></>}
function TechSchedule(){return <><PageTitle title="Schedule" subtitle="Your daily and weekly appointment calendar."/><div className="calendar-head"><Button variant="soft">‹</Button><b>September 01, 2026</b><Button variant="soft">›</Button><Button>Today</Button></div><div className="schedule"><div className="schedule-hours">{['08:00 AM','09:00 AM','10:00 AM','11:00 AM','12:00 PM','01:00 PM','02:00 PM','03:00 PM','04:00 PM'].map(x=><span key={x}>{x}</span>)}</div><div className="schedule-events"><div className="event done" style={{top:'21%'}}><b>Washing Machine Repair</b><small>09:00 – 10:00 · Carlos</small></div><div className="event current" style={{top:'34%'}}><b>AC Repair</b><small>10:00 – 11:30 · Aisha Rahman</small></div><div className="event" style={{top:'54%'}}><b>Deep Cleaning</b><small>12:00 – 02:00 · Omar Abdullah</small></div><div className="event" style={{top:'77%'}}><b>AC Installation</b><small>02:30 – 04:00 · Liam Nguyen</small></div></div></div></>}
function TechEarnings(){return <><PageTitle title="Earnings" subtitle="Track completed jobs, payments and monthly income."/><div className="stats"><Stat value="AED 8,450" label="This Month" trend="14%" icon={<CircleDollarSign/>}/><Stat value="AED 94,200" label="Total Earnings" icon={<WalletCards/>}/><Stat value="248" label="Completed Jobs" icon={<CheckCircle2/>}/><Stat value="AED 1,200" label="Pending Payout" icon={<Clock3/>}/></div><Card title="Recent Earnings"><TableWrap><table><thead><tr><th>Job</th><th>Customer</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>{bookings.slice(0,6).map(b=><tr key={b.id}><td className="linkish">{b.id} · {b.service}</td><td>{b.customer}</td><td>{b.date}</td><td><b>{b.amount}</b></td><td><Status>Paid</Status></td></tr>)}</tbody></table></TableWrap></Card></>}
function TechReviews(){return <><PageTitle title="My Reviews" subtitle="See what customers say about your service."/><div className="review-summary"><Card><div className="score"><strong>4.9</strong><div>★★★★★</div><span>248 ratings</span></div></Card><Card title="Rating Breakdown"><Progress name="5 ★" value={96}/><Progress name="4 ★" value={3}/><Progress name="3 ★" value={1}/></Card></div><div className="review-grid">{reviews.slice(0,4).map(r=><div className="review-card" key={r.name}><div className="person"><Avatar name={r.name}/><div><b>{r.name}</b><small>{r.service}</small></div></div><div className="stars">★★★★★</div><p>“{r.text}”</p><small>2 days ago</small></div>)}</div></>}

function UserDashboard({go}){return <><PageTitle title="Welcome back, Aisha 👋" subtitle="Find trusted professionals and manage your home services."/><div className="customer-banner"><div><span>Need a service today?</span><h2>Book a professional in minutes.</h2><p>Choose a service, select a time and we’ll handle the rest.</p><Button onClick={()=>go('Services')}>Browse Services</Button></div><div className="banner-art">🛠️</div></div><div className="section-head"><h2>Upcoming Booking</h2><Button variant="link" onClick={()=>go('My Bookings')}>View all</Button></div><div className="upcoming-card"><div className="service-icon">❄️</div><div className="grow"><span className="linkish">BK-1042</span><h3>AC Repair</h3><p><CalendarDays/> Sep 01, 2026 · 10:00 AM</p><p><MapPin/> Dubai Marina</p></div><div className="tech-mini"><Avatar name="Ravi Kumar"/><div><b>Ravi Kumar</b><small>Technician · ★ 4.9</small></div></div><Status>Confirmed</Status></div><div className="section-head"><h2>Popular Services</h2><Button variant="link" onClick={()=>go('Services')}>See all</Button></div><div className="customer-services">{services.slice(0,4).map(s=><div className="customer-service" key={s.name}><div className="service-icon">{s.icon}</div><h3>{s.name}</h3><p>{s.description}</p><b>{s.price}</b><Button variant="small soft" onClick={()=>go('Services')}>Book now</Button></div>)}</div></>}
function UserServices({open}){const[q,setQ]=useState('');const rows=services.filter(s=>Object.values(s).join(' ').toLowerCase().includes(q.toLowerCase())&&s.status==='Active');return <><PageTitle title="Services" subtitle="Choose from our trusted home and business services."/><div className="customer-search"><Search size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="What service do you need?"/><Button>Search</Button></div><div className="category-pills"><button className="active">All</button><button>HVAC</button><button>Plumbing</button><button>Electrical</button><button>Cleaning</button><button>Appliances</button><button>Renovation</button></div><div className="service-grid customer-service-grid">{rows.map(s=><div className="service-card" key={s.name}><div className="service-icon">{s.icon}</div><span className="category">{s.category}</span><h3>{s.name}</h3><p className="description">{s.description}</p><div className="service-meta"><div><b>{s.price}</b><small>{s.duration}</small></div><div><b>★ 4.8</b><small>{s.bookings}+ bookings</small></div></div><Button onClick={()=>open({title:`Book ${s.name}`,service:s,bookingForm:true})}>Book Service</Button></div>)}</div></>}
function UserBookings({open}){return <><PageTitle title="My Bookings" subtitle="Track your current and previous service appointments." action={<Button onClick={()=>open({title:'New Booking',bookingForm:true})}><Plus size={16}/>New Booking</Button>}/><div className="tabs"><button className="active">Upcoming (2)</button><button>In Progress (1)</button><button>Completed (8)</button><button>Cancelled (1)</button></div><div className="booking-list">{bookings.slice(0,6).map((b,i)=><div className="customer-booking" key={b.id}><div className="booking-icon">{services.find(s=>s.name===b.service)?.icon||'🔧'}</div><div className="grow"><div className="booking-title"><span className="linkish">{b.id}</span><Status>{i===0?'Confirmed':i===1?'In Progress':'Completed'}</Status></div><h3>{b.service}</h3><p><CalendarDays/> {b.date} · {b.time}</p><p><MapPin/> {b.address}</p></div><div className="booking-right"><b>{b.amount}</b><Button variant="small soft" onClick={()=>open({title:`Booking ${b.id}`,booking:b,customerBooking:true})}>View Details</Button></div></div>)}</div></>}
function UserPayments({open}){return <><PageTitle title="Payments" subtitle="Manage payment methods and view your transaction history." action={<Button onClick={()=>open({title:'Add Payment Method',form:true})}><Plus size={16}/>Add Card</Button>}/><Card title="Saved Payment Methods"><div className="payment-methods"><div className="payment-card"><CreditCard/><div><b>•••• •••• •••• 4242</b><small>Visa · Expires 08/28</small></div><span>Default</span></div><div className="payment-card muted"><CreditCard/><div><b>•••• •••• •••• 7788</b><small>Mastercard · Expires 11/27</small></div><Button variant="small soft">Set Default</Button></div></div></Card><Card title="Transaction History" className="mt20"><TableWrap><table><thead><tr><th>Transaction</th><th>Service</th><th>Date</th><th>Amount</th><th>Status</th><th>Receipt</th></tr></thead><tbody>{bookings.slice(0,6).map((b,i)=><tr key={b.id}><td className="linkish">TX-{5521-i}</td><td>{b.service}</td><td>{b.date}</td><td><b>{b.amount}</b></td><td><Status>Paid</Status></td><td><Button variant="small soft" onClick={()=>open({title:'Payment Receipt',payment:b})}>View Receipt</Button></td></tr>)}</tbody></table></TableWrap></Card></>}
function UserReviews({open}){return <><PageTitle title="My Reviews" subtitle="Rate your completed services and see your submitted feedback."/><div className="pending-review"><div className="service-icon">🔧</div><div className="grow"><span>Completed · Aug 31, 2026</span><h3>Washing Machine Repair</h3><p>Technician: Ravi Kumar</p></div><Button onClick={()=>open({title:'Write a Review',reviewForm:true})}>Rate Service</Button></div><div className="section-head"><h2>Submitted Reviews</h2></div><div className="review-grid">{reviews.slice(0,4).map(r=><div className="review-card" key={r.name}><div className="stars">★★★★★</div><h3>{r.service}</h3><small>Technician: Ravi Kumar</small><p>“{r.text}”</p><Button variant="small soft">Edit Review</Button></div>)}</div></>}
function ProfilePage({role}){const data=role==='technician'?['Ravi Kumar','ravi@clientservices.com','+971 50 222 1111','AC & Refrigeration']:['Aisha Rahman','aisha@email.com','+971 50 123 4567','Customer'];return <><PageTitle title="Profile" subtitle="Manage your personal information and account details."/><Card><div className="profile-header"><Avatar name={data[0]} size="xl"/><div><h2>{data[0]}</h2><p>{data[3]}</p><Button variant="soft"><Camera size={15}/>Change Photo</Button></div></div><div className="form-grid"><Field label="Full Name" value={data[0]}/><Field label="Email" value={data[1]}/><Field label="Phone" value={data[2]}/><Field label="Location" value="Dubai, UAE"/><Field label="Password" value="••••••••"/><Field label="Language" value="English" select/></div><div className="form-actions"><Button>Save Changes</Button></div></Card></>}

function Modal({data,onClose}){if(!data)return null;return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="modal-head"><h2>{data.title}</h2><button onClick={onClose}><X/></button></div>{data.form&&<FormContent kind={data.title} onClose={onClose}/>} {data.bookingForm&&<BookingForm service={data.service} onClose={onClose}/>} {data.reviewForm&&<ReviewForm onClose={onClose}/>} {data.confirm&&<div className="confirm"><AlertCircle/><h3>{data.title}?</h3><p>This changes service availability for future bookings.</p><div><Button variant="soft" onClick={onClose}>Cancel</Button><Button onClick={onClose}>Confirm</Button></div></div>}{data.booking&&!data.form&&!data.bookingForm&&<DetailBooking b={data.booking} tech={data.technicianJob} customer={data.customerBooking}/>} {data.customer&&<CustomerDetail c={data.customer}/>} {data.technician&&<TechDetail t={data.technician}/>} {data.service&&!data.form&&!data.bookingForm&&!data.confirm&&<ServiceDetail s={data.service}/>} {data.payment&&<PaymentDetail p={data.payment}/>} {data.title==='Notifications'&&<Notifications/>}</div></div>}
function DetailBooking({b,tech,customer}){return <div className="detail"><div className="detail-banner"><Status>{b.status}</Status><span>{b.id}</span></div><h3>{b.service}</h3><div className="detail-grid"><Detail label="Customer" value={b.customer}/><Detail label="Technician" value={b.tech}/><Detail label="Date & Time" value={`${b.date} · ${b.time}`}/><Detail label="Location" value={b.address}/><Detail label="Amount" value={b.amount}/><Detail label="Payment" value="Credit Card · Paid"/></div>{tech&&<div className="progress-steps"><span className="done"><Check/>Accepted</span><span className="done"><Wrench/>In Progress</span><span><CheckCircle2/>Complete</span></div>}{customer&&<Button><Navigation size={15}/>Track Technician</Button>}</div>}
function Detail({label,value}){return <div><small>{label}</small><b>{value}</b></div>}
function CustomerDetail({c}){return <div className="detail"><div className="profile-header compact-profile"><Avatar name={c.name} size="large"/><div><h3>{c.name}</h3><p>{c.email}</p></div></div><div className="detail-grid"><Detail label="Phone" value={c.phone}/><Detail label="Status" value={c.status}/><Detail label="Bookings" value={c.bookings}/><Detail label="Total Spent" value={c.spent}/></div></div>}
function TechDetail({t}){return <div className="detail"><div className="profile-header compact-profile"><Avatar name={t.name} size="large"/><div><h3>{t.name}</h3><p>{t.specialty} · ★ {t.rating}</p></div></div><div className="detail-grid"><Detail label="Status" value={t.status}/><Detail label="Area" value={t.area}/><Detail label="Phone" value={t.phone}/><Detail label="Completed Jobs" value={t.jobs}/></div><Button><Phone size={15}/>Contact Technician</Button></div>}
function ServiceDetail({s}){return <div className="detail"><div className="service-hero"><div className="service-icon">{s.icon}</div><div><h3>{s.name}</h3><p>{s.category}</p></div></div><p className="detail-description">{s.description}</p><div className="detail-grid"><Detail label="Starting Price" value={s.price}/><Detail label="Duration" value={s.duration}/><Detail label="Bookings" value={s.bookings}/><Detail label="Status" value={s.status}/></div></div>}
function PaymentDetail({p}){return <div className="detail"><div className="receipt"><CheckCircle2/><h3>Payment Successful</h3><strong>{p.amount}</strong><span>Transaction TX-5521</span></div><div className="detail-grid"><Detail label="Booking" value={p.id}/><Detail label="Service" value={p.service}/><Detail label="Date" value={p.date}/><Detail label="Method" value="Visa •••• 4242"/></div></div>}
function Notifications(){return <div className="notifications"><Activity icon={<CalendarCheck/>} text="New booking received" time="5 min ago"/><Activity icon={<CreditCard/>} text="Payment received successfully" time="18 min ago"/><Activity icon={<Star/>} text="You received a new review" time="42 min ago"/><Activity icon={<AlertCircle/>} text="Your profile needs verification" time="Yesterday"/></div>}
function FormContent({kind,onClose}){return <form onSubmit={e=>{e.preventDefault();onClose()}}><div className="form-grid"><Field label="Name" value=""/><Field label="Email" value=""/><Field label="Phone" value=""/><Field label="Status" value="Active" select/><Field label="Date" value="Sep 02, 2026"/><Field label="Time" value="10:00 AM"/></div><div className="form-actions"><Button variant="soft" onClick={onClose}>Cancel</Button><Button type="submit">Save {kind.includes('Booking')?'Booking':'Changes'}</Button></div></form>}
function BookingForm({service,onClose}){return <form onSubmit={e=>{e.preventDefault();onClose()}}><div className="booking-form-service"><span className="service-icon">{service?.icon||'🔧'}</span><div><b>{service?.name||'Select a service'}</b><small>{service?.price||'Choose a service and date'}</small></div></div><div className="form-grid"><Field label="Service" value={service?.name||'AC Repair'} select/><Field label="Technician" value="Any available technician" select/><Field label="Date" value="Sep 03, 2026"/><Field label="Time" value="10:00 AM"/><Field label="Address" value="Dubai Marina, UAE"/><Field label="Notes" value="Please call before arrival"/></div><div className="form-actions"><Button variant="soft" onClick={onClose}>Cancel</Button><Button type="submit">Confirm Booking</Button></div></form>}
function ReviewForm({onClose}){return <form onSubmit={e=>{e.preventDefault();onClose()}}><h3>How was your service?</h3><div className="rating-picker">★★★★★</div><label className="field"><span>Your Review</span><textarea placeholder="Tell us about your experience..."/></label><div className="form-actions"><Button variant="soft" onClick={onClose}>Cancel</Button><Button type="submit">Submit Review</Button></div></form>}

function Shell({role,setRole,page,setPage,children,open}){const nav=role==='admin'?adminNav:role==='technician'?techNav:userNav;const names={admin:'Admin',technician:'Ravi Kumar',user:'Aisha Rahman'};return <div className="app"><aside><div className="brand"><div className="brand-mark">CS</div><div>CLIENT <span>SERVICES</span></div></div><div className="role-switch"><span>VIEW AS</span><select value={role} onChange={e=>{setRole(e.target.value);setPage('Dashboard')}}><option value="admin">Admin Panel</option><option value="technician">Technician Panel</option><option value="user">User Panel</option></select></div><nav>{nav.map(([name,Icon])=><button key={name} className={page===name?'selected':''} onClick={()=>setPage(name)}><Icon size={20}/><span>{name}</span></button>)}</nav><div className="sidebar-bottom"><button onClick={()=>open({title:'Notifications'})}><Bell size={19}/><span>Notifications</span><i>3</i></button><button><LogOut size={19}/><span>Sign Out</span></button></div></aside><main><header><div className="mobile-menu"><Menu/></div><div><h2>{page}</h2><small>{role==='admin'?'Management console':role==='technician'?'Technician workspace':'Customer portal'}</small></div><div className="header-right"><button className="icon-btn" onClick={()=>open({title:'Notifications'})}><Bell size={20}/><i>3</i></button><div className="header-profile"><Avatar name={names[role]}/><div><b>{names[role]}</b><small>{role==='admin'?'Administrator':role==='technician'?'Technician':'Customer'}</small></div></div></div></header><div className="content">{children}</div></main></div>}
function App(){const[role,setRole]=useState('admin'),[page,setPage]=useState('Dashboard'),[modal,setModal]=useState(null);const go=p=>setPage(p);let content;if(role==='admin'){content=page==='Dashboard'?<AdminDashboard go={go}/>:page==='Bookings'?<AdminBookings open={setModal}/>:page==='Customers'?<AdminCustomers open={setModal}/>:page==='Technicians'?<AdminTechnicians open={setModal}/>:page==='Services'?<AdminServices open={setModal}/>:page==='Payments'?<AdminPayments open={setModal}/>:page==='Reviews'?<AdminReviews/>:page==='Reports'?<AdminReports/>:<SettingsPage role="admin"/>}else if(role==='technician'){content=page==='Dashboard'?<TechDashboard go={go}/>:page==='My Jobs'?<TechJobs open={setModal}/>:page==='Schedule'?<TechSchedule/>:page==='Earnings'?<TechEarnings/>:page==='Reviews'?<TechReviews/>:page==='Profile'?<ProfilePage role="technician"/>:<SettingsPage role="technician"/>}else{content=page==='Dashboard'?<UserDashboard go={go}/>:page==='Services'?<UserServices open={setModal}/>:page==='My Bookings'?<UserBookings open={setModal}/>:page==='Payments'?<UserPayments open={setModal}/>:page==='Reviews'?<UserReviews open={setModal}/>:page==='Profile'?<ProfilePage role="user"/>:<SettingsPage role="user"/>}return <><Shell role={role} setRole={setRole} page={page} setPage={setPage} open={setModal}>{content}</Shell><Modal data={modal} onClose={()=>setModal(null)}/></>}
createRoot(document.getElementById('root')).render(<App/>);
